spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.0"
accounts:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Saravanapandiyan - Developer"
    email: "spandiyan@eazybank.com"
  onCallSupport:
    - (111) 555-1234
    - (111) 523-1345